version: '3.7'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    ports:
      - "5432:5432"
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - postgres
  todo-service:
    build:
      context: ./todo-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    depends_on:
      - postgres
